services:
  - type: web
    name: molty5
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main
    envVars:
      - key: AGENT_NAME
        value: MexL
      - key: ROOM_MODE
        value: free
      - key: LOG_LEVEL
        value: INFO
      - key: ADVANCED_MODE
        value: true
      - key: AUTO_WHITELIST
        value: true
      - key: AUTO_SC_WALLET
        value: true
      - key: ENABLE_MEMORY
        value: true
      - key: ENABLE_AGENT_TOKEN
        value: false
      - key: AUTO_IDENTITY
        value: true
    autoDeploy: true